### ISSUE TITLE
Unit 3 Homework

### ISSUE THREAD

**Issue by AlexFedosenko** [VictorKazankov/MyHometaskForGoJava#2]
В целом, неплохо. Есть 2 замечания:
1. Я заметил, что ты используешь массивы в таких классах, как DirectoryWindows. Это твое право, такое решение имеет право на жизнь. Если есть желание, можно начать ознакамливаться с Коллекциями в Java. Они тут будут уместнее. Но что неправильно, так это то, что в MusicShop'е у тебя может находиться лишь один инструмент. Не больше.
2. Я заметил у тебя строку "private Rose rose[];". Похвально, что ты используешь модификаторы доступа, в данном случае "private". Предлагаю посмотреть на них еще и для всех полей проставить соответствующие модификаторы. Они действительно важны в Java и особенно при наследовании, так что пригодится особое внимание.
3. Не критично, но рекомендую добавить в .gitignore папку .idea и все файлы с расширением .iml. Это все файлы, сгенерированные Intellij Idea. По хорошему, репозиторий не должен зависеть от IDE, в котором работает разработчик. Заодно попрактикуешься в работе с git'ом еще чуть-чуть.

**Comment by VictorKazankov** [comment]
1. Добавил массив экземпляров класса в MisucShop.
2. Проставил модификаторы доступа для всех полей.
3. Добавил все
